# -*- coding: utf-8 -*-
"""irisClassification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jiHO6mWUIVW45KfozhuIADPS5r4fph4E
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.DataFrame(pd.read_csv('Iris.csv'))

df.head()
df.tail()
df.describe()

df.groupby('Species').size()

X = df.iloc[:, 1:5]
y = pd.DataFrame(df.iloc[:, 5])

X

y

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['Species'] = le.fit_transform(y['Species'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

X_train

y_train

y_test

plt.figure()
sns.pairplot(df.drop("Id", axis=1), hue = "Species", height=3, markers=["o", "s", "D"])
plt.show()

from sklearn.linear_model import LogisticRegression
Lr = LogisticRegression()
Lr.fit(X_train,y_train)

Lr.score(X_train,y_train)

y_pred = Lr.predict(X_test)

print(le.inverse_transform(y_pred))